### ISSUE TITLE
Issues following tutorial

### ISSUE THREAD

**Issue by KeeganTP** [dfm/astropy-transit-periodogram#5]
Hi!

I'm attempting to implement your bls package, but have run into an error while following the tutorial you uploaded. When attempting to import bls, Python returns:

>>> from bls import BLS

Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    from bls import BLS
  File "/run/media/thomson/920A-4120/MASCARA/bls/__init__.py", line 14, in <module>
    from .core import BLS, BLSResults
  File "/run/media/thomson/920A-4120/MASCARA/bls/core.py", line 11, in <module>
    from . import methods
  File "/run/media/thomson/920A-4120/MASCARA/bls/methods.py", line 8, in <module>
    from ._impl import bls_impl
ImportError: No module named _impl

I've tried looking into the files to see if I can resolve the issue, but to no avail. Any chance you can update the file or indicate what I need to change in order to make it work?

Thanks in advance!

**Comment by dfm** [comment]
I'd recommend trying out the development version of astropy because there's a better implementation (based on this one) there: https://astropy.readthedocs.io/en/latest/stats/bls.html

But, if you definitely want to use this, you're probably getting that error because you're trying to run within the git directory and the compiled extension isn't in the right place. To fix that you'll need to install using `python setup.py develop` or `python setup.py build_ext --inplace`.

**Comment by KeeganTP** [comment]
Hi Dan,

Thanks for getting back to me! I'll give the Astropy option a go first, and
see how I go. I honestly didn't think there it had a BLS class which was
confirmed, or at least I thought, by doing a quick google search.

Thanks again!

Keegan
